POST http://localhost:5125/perfumes
Content-Type: application/json

{
    "name": "Greenwich Village",
    "volume": 100
}

###

GET http://localhost:5125/perfumes/1

###

POST http://localhost:5125/bottles
Content-Type: application/json

{
    "volume": 11,
    "priceperml": 17.50,
    "type": "Encomenda",
    "perfumeid": 1

}

###
GET http://localhost:5125/bottles/2